# Generated by Django 2.1.7 on 2019-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='Time of the event', verbose_name='Time of the event')),
                ('title', models.CharField(help_text='Title of the event', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the event', null=True, verbose_name='Description of the event')),
            ],
        ),
    ]
