# Generated by Django 2.1.7 on 2019-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='added_by',
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='User Email'),
        ),
    ]
